[package]
name = "init"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "palmeto"
path = "src/main.rs"

[dependencies]
limine = { workspace = true }

shared = { path = "../shared" }
kernel = { path = "../kernel" }
drivers = { path = "../drivers" }

fdt = { workspace = true }
spin = { workspace = true }