[package]
name = "init"
version.workspace = true
edition.workspace = true

[[bin]]
name = "palmeto"
path = "src/main.rs"

[dependencies]
limine = { workspace = true }

shared = { path = "../shared" }
kernel = { path = "../kernel" }
drivers = { path = "../drivers" }

fdt = { workspace = true }
spin = { workspace = true }