[workspace]
members = [
    "kernel",
    "drivers",
    "shared",
    "boot",
]
resolver = "2"

[workspace.dependencies]
limine = { path = "bindings/limine-rs" }
flanterm = { path = "bindings/flanterm-rs" }

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = "debuginfo"