[package]
name = "kernel"
version.workspace = true
edition.workspace = true

[dependencies]
limine   = { workspace = true }
flanterm = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }

shared = { path = "../shared" }
spin   = { workspace = true }
fdt    = { workspace = true }